language: python

before_install:
  - cd gym_jsbsim
# - git clone https://github.com/JSBSim-Team/jsbsim.git
  - cd ..

matrix:
  include:
    - name: "Python 3.7 on Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell

install:
  - pip3 install .

# command to run tests
script:
  - python3 -m unittest

after_success:
  - python setup.py bdist_wheel
  
deploy:
  provider: pypi
  username: __token__
  password: 
    secure: pypi-AgEIcHlwaS5vcmcCJDRiMDkxY2UzLTY1ODQtNGQ1Ni05NjhmLTM2NGNhMDlkNWJkZAACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYgErj9tV8NxVaK72fN9EjPOl4ypkRP0KAJ3GW8jMRrkFU
  distributions: bdist_wheel
  skip_existing: true
  branches:
    only:
      - new
