language: python

matrix:
  include:
    - name: "Python 3.7 on Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
    - name: "Python 3.7 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python3 --version=3.7.5
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH

install:
  - pip3 install --upgrade pip  # all three OSes agree about 'pip3'
  - pip3 install .

# command to run tests
script:
  - python3 -m unittest || python -m unittest

after_success:
  - python setup.py bdist_wheel
  
deploy:
  provider: pypi
  username: galleon
  password:
    secure: "tKVYK5SsN/0PZtu/gy8oa2YN4P3YlIVdaW00Kot5KRhFL5MZQjY4tVNM8x0xDtACAw3a42o37C2k6njAyqjLquaSmvfxWQ4G4ItRbpOEnnqyjWrEu/2qDBiHJV36fHVObycv64B9c3d3hz4m+00wc1tVhl7BM3xfMRqQWWD4m1xJ5VqX/agr35DbNf43SEQja3OZYceSir+EBBEonyKG7ZmCxhmyRkv25RVn9FenO16sC35yeQ2hnmv3Z0o4VjN2kG/AVlfzJKaeAwJOuwQ3m5AHV6WW3Giek2W0eC3Y6K+STvMnyN6h99LBpD4Bmjjxq1kn5+ZQ14uNlHNYEQTk4HpkI6yzap9JpHEmjNivtnWTCY3CFAy36ChVMaYK/DYUDRuE65E2688bsyVaz9o4G+c7RlZiOf2LsxOdfSkPyJCW9iJ8MHTbx6Sodn6pTxxMMtotFsWdOaqMV6MfpHkXXnVmjX7cw2Q62qhNa7HA0miFO2rVIyN5NbqF4tB1v0APklZm8lGhLmSjw5YtUOq9BZtiWG9cv2AJBoh11D7MFdZ+RgAkVbbp1lbhaM4YViPrAWEemJnWdpJ7/NmfPWMPzVF00gJ4hzOb0aZCJB2NO/ozKvLoGIBFEUH12lErMV6nwt8XuSiyoWuHPqJN14ERx73UJrs9Iz9nQxe9ycktyHQ="
  distributions: bdist_wheel
  skip_existing: true
  branches:
    only:
      - new
