language: python

before_install:
  - git clone --branch new https://github.com/galleon/gym-jsbsim.git
  - cd gym-jsbsim/gym_jsbsim
  - git clone https://github.com/JSBSim-Team/jsbsim.git
  - cd ..

matrix:
  include:
    - name: "Python 3.7 on Linux"
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      install:
        - pip3 install .
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode11    # Python 3.7 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      services:
        - docker
      install:
        - docker build -t docker_gym_jsbsim
        - docker run -v "$PWD":/home/gym-jsbsim -it docker_gym_jsbsim
  
# command to run tests
script:
  - python3 -m unittest
