language: python
matrix:
  include:
  - name: Python 3.7 on Linux
    python: 3.7
  - name: Python 3.7 on macOS
    os: osx
    osx_image: xcode11
    language: shell
  - name: Python 3.7 on Windows
    os: windows
    language: shell
    before_install:
    - choco install python --version=3.7.4
    - python -m pip install --upgrade pip
    - pip install https://download.lfd.uci.edu/pythonlibs/g5apjq5m/Shapely-1.6.4.post2-cp37-cp37m-win_amd64.whl
      wheel
    - sed -i 's/<expat.h>/"expat.h"/' gym_jsbsim/jsbsim/src/simgear/xml/easyxml.cxx
    - sed -i 's/std::min/(std::min)/' gym_jsbsim/jsbsim/src/simgear/misc/strutils.cxx
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
- pip3 install .
script:
- python3 -m unittest || python -m unittest
deploy:
  provider: pypi
  username: galleon
  password:
    secure: Dj25UHJRIagIOUSyofGQhJpYSUH6MuFoPt80jAuseDBUwgsTYUCldFybl8ZitbZ93NHS4SSKUoitz59VCerrhpjATSQzcSPHsbS2FIu6kBu7c8tHUvfy4c+KTuE0ui/hY8ylTcdz9hnO1gezwR2/OwsPhrhhnDGkHMWusmCazk9FdYDk0Bf2Upcbxl76aV7WbNMbhrFyRN/F69EK4Y3CQGfAARC6u5K2JiaWM7T8UP66axt/YUqIfCei8rjUgwI9z470fOolxbqygUXA0MUHawMNDz73VMhZvhis0EZDn+B5/wDDObEDZ6ZwkcgziIxlIJlyhL02UIXn1eQxM1K2RQw0oObxfPI1mfap58ormsfwYlYZENI4WMCZppRdHMQG852WsqJh21MHmKGLVrnNcJ5Py9lJtG+G/oqg8rbdWx+M2TFS5a9oPZ6FiTOvQNxtWPomDeisBrab6tBcPWeKAfikI9xZp0FOxMPydMKv58TT7dF40M2/qnXkmJTl9tRjLbPe+/C2svGSzDZUfgA0npL6IvFJ2n0rAkZiwnp8ieIleaVYcsEh75te+T/VaZ0FUfuChC3mGdYzQT05xrQvFnBCrhRueFnZjqf5VI/oDgCzOo5STIRzXRFGZ1Hd5DESP1sjvxbBDQd1uyyRd8xEUvWPQMjYDyGt4oL4ozmDx6g=
  distributions: bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    python: 3.7
    branch: new
