language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install matplotlib
  - pip install geopandas
  - pip install geographiclib
  - pip install shapely
  - pip install .
# command to run tests
script:
  - python -m unittest
